---
name: Feature Request
description: Suggest a new feature for Specto.
title: "feature: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Overview
      description: Include the basic, high-level concepts for this feature here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Smaller details
      description: These may include specific methods of implementation etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why would this feature be useful?
      description: Remember that Specto should not solve every problem, but provide the hooks required to solve them.
    validations:
      required: true
